version: "3.7"
services:
  test:
    container_name: test
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.test
    env_file:
      - .env
    environment:
      - DB_URL=mongodb://mongo:27017/cryptocompare
      - TEST_DB_URL=mongodb://mongo:27017/cryptocomparetest

    links:
      - mongo
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    # ports:
    #   - "27018:27017"