version: "3.7"
services:
  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    links:
      - mongo
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    # ports:
    #   - "27018:27017"